# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hero', models.CharField(max_length=10)),
                ('heroine', models.CharField(max_length=10)),
            ],
        ),
    ]
